environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  RUST_BACKTRACE: full
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\Users\appveyor\
  - rustc -vV
  - cargo -vV
  - curl -LsSf -o z3.zip https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-win.zip
  - unzip z3.zip
  - mv z3-4.5.0-x64-win/bin/z3.exe C:\Users\appveyor\z3.exe
build: false
test_script:
  - cargo build --verbose
  - cargo test --verbose